services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test1234!
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
